version: "3.8"

services:
  web:
    build:
      context: .
    container_name: fastapi-app
    ports:
      - "443:443"
    volumes:
      - ./app:/app
      - /root/ssl:/ssl:ro
    working_dir: /app
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 443
      --ssl-keyfile /ssl/server.key
      --ssl-certfile /ssl/server.crt
